"""allow users without passwords

Revision ID: 8981133f520e
Revises: 0ce2615d7026
Create Date: 2026-09-05 22:06:12.134094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8981133f520e'
down_revision = '0ce2615d7026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
